server:
  port: 8081

spring:
  application:
    name: generator-service


logging:
  level:
    org.org.springframework.web: DEBUG
    com.akirolabs.generator: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
application:
    cors:
      allowed-origin-patterns: "http://localhost:8080"
      allowed-path: "/api/**"